name = "vaai-backend-worker"
main = "src/index.ts"
compatibility_date = "2024-10-30"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "vaai-db"
database_id = "82a1eb01-5f21-4d97-9a93-1e2cee526069"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "99f6cccf90df48dea49b9f22a91d1317"